### PR TITLE
Added .Net Path to remote options

### PR DESCRIPTION
**Pull request by vnbaaij**
Added '-r linux-arm' to publish command
Changed some path references to ~/
Corrected some typo's

### CODE REVIEW

**Comment by radutomy** [comment]
Great, thanks for this! Have you tested these changes? I don't have a Pi with me right now so I can't do it myself.

**Comment by vnbaaij** [comment]
Yes, I have tested it and it all works!

**Comment by vnbaaij** [comment]
How hard is it to add another menu option? I would like to have one that basically does all the same steps but just not the debugging (so build and publish)

**Comment by radutomy** [comment]
Not too hard. I'll be spending a couple of hours over the weekend on this project, so if you add a feature request I'll look into it.

**Pull request merged**
